### ISSUE TITLE
[FEATURE] - Create Hero Section

### ISSUE THREAD

**Issue by riyavishwa981** [tcet-opensource/tcet-website#2]
![image](https://github.com/tcet-opensource/tcet-website/assets/79577834/99e607d7-8e15-4927-9898-b0e4041bd81a)

- For your understanding you have to create this part
- Make it responsive
- Make correct use of fonts and colors refer the [design](https://www.figma.com/file/0eS7ipdRxGmxUisPBu1xSH/tcetmumbai.in?type=design&node-id=442-10808&t=CdgN38w4pSlb4VVK-0) for the same
- Make branch name as issue_no-hero-section

**Comment by JayeshVP24** [comment]
#15
