### ISSUE TITLE
[FEATURE] - Create Certified By Section

### ISSUE THREAD

**Issue by riyavishwa981** [tcet-opensource/tcet-website#3]
![image](https://github.com/tcet-opensource/tcet-website/assets/79577834/d47205cb-10e2-4850-ac27-2c803b061055)
- For your understanding you have to create this whole part
- Make it responsive

- Make correct use of fonts and colors refer the [design](https://www.figma.com/file/0eS7ipdRxGmxUisPBu1xSH/tcetmumbai.in?type=design&node-id=442-10808&t=CdgN38w4pSlb4VVK-0) for the same
- Make branch name as issue_no-certified-by-section
- You can reuse components from any previous repo

**Comment by JayeshVP24** [comment]
#17
