### ISSUE TITLE
[FEATURE] - Create About Tcet Section

### ISSUE THREAD

**Issue by riyavishwa981** [tcet-opensource/tcet-website#4]
![image](https://github.com/tcet-opensource/tcet-website/assets/79577834/db2451d5-d248-4085-b79a-6179aaf414ce)

- For your understanding you have to create this part
- Make it responsive
- Make correct use of fonts and colors refer the [design](https://www.figma.com/file/0eS7ipdRxGmxUisPBu1xSH/tcetmumbai.in?type=design&node-id=442-10808&t=CdgN38w4pSlb4VVK-0) for the same
- Make branch name as issue_no-about-tcet-section
- Reuse the components if you want to

**Comment by JayeshVP24** [comment]
#20 solved here
