### ISSUE TITLE
[FEATURE] - Create Programmes Section

### ISSUE THREAD

**Issue by riyavishwa981** [tcet-opensource/tcet-website#7]
![image](https://github.com/tcet-opensource/tcet-website/assets/79577834/8f4137d3-18a9-4ae8-b943-7064cd9fb811)

- For your understanding you have to create this part
- Make it responsive
- Make correct use of fonts and colors refer the [design](https://www.figma.com/file/0eS7ipdRxGmxUisPBu1xSH/tcetmumbai.in?type=design&node-id=442-10808&t=CdgN38w4pSlb4VVK-0) for the same
- Make branch name as issue_no-programmes-section
- You can reuse components if you want to

**Comment by JayeshVP24** [comment]
#19
